/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import controller.RentalController;
/**
 *
 * @author Abin Tara
 */
public class RentalForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RentalForm.class.getName());

    public static int idUserLogin = 1; // Default 1 untuk testing mandiri
    private final controller.RentalController controller = new controller.RentalController();
    
    /**
     * Creates new form RentalForm
     */
    public RentalForm() {
        initComponents();
        loadDataCustomerDariSQL();   
        loadDataKendaraanDariSQL();  
        loadDataTransaksiKeTable();
    }
    
    private void updateOtomatisTotalBayar() {
    String lamaSewaRaw = txtLamaSewa.getText();
    String hargaSewaRaw = txtHargaSewa.getText();
    
    //Minta Controller buat menghitung, lalu langsung set hasilnya ke textfield
    String hasilHitungan = controller.hitungTotalBayar(lamaSewaRaw, hargaSewaRaw);
    txtTotalHarga.setText(hasilHitungan);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTglPinjam = new javax.swing.JTextField();
        txtLamaSewa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cmbCustomer = new javax.swing.JComboBox<>();
        cmbKendaraan = new javax.swing.JComboBox<>();
        txtMerekKendaraan = new javax.swing.JTextField();
        txtHargaSewa = new javax.swing.JTextField();
        txtTotalHarga = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Transaksi Peminjaman Kendaraan");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Rincian Peminjaman"));

        jLabel3.setText("Tanggal Peminjaman");

        jLabel4.setText("Lama Sewa (Hari)");

        txtTglPinjam.setText("YYYY-MM-DD");
        txtTglPinjam.addActionListener(this::txtTglPinjamActionPerformed);

        txtLamaSewa.setText("0");
        txtLamaSewa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLamaSewaKeyReleased(evt);
            }
        });

        jLabel5.setText("Pilih Nama Customer");

        jLabel6.setText("Pilih Plat Kendaraan");

        jLabel7.setText("Merek Kendaraan");

        jLabel8.setText("Harga Sewa");

        jLabel9.setText("Total Bayar");

        cmbKendaraan.addItemListener(this::cmbKendaraanItemStateChanged);

        txtMerekKendaraan.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                txtMerekKendaraanComponentResized(evt);
            }
        });
        txtMerekKendaraan.addActionListener(this::txtMerekKendaraanActionPerformed);

        txtHargaSewa.addActionListener(this::txtHargaSewaActionPerformed);

        jButton1.setText("Cancel");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setForeground(new java.awt.Color(255, 51, 51));
        jButton2.setText("Delete");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Simpan Transaksi");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLamaSewa)
                            .addComponent(txtTglPinjam, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)))
                    .addComponent(jLabel4))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel9)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(42, 42, 42)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cmbCustomer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbKendaraan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMerekKendaraan)
                    .addComponent(txtHargaSewa)
                    .addComponent(txtTotalHarga))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmbCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cmbKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTglPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtLamaSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtMerekKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtHargaSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No. Nota", "Nama Pelanggan", "Kendaraan", "Tgl. Pinjam", "Lama Sewa", "Total Bayar"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(9, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(259, 259, 259))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        // Ambil data teks mentah apa adanya dari komponen visual UI
        String selectedCustomer = cmbCustomer.getSelectedItem().toString();
        String selectedVehicle = cmbKendaraan.getSelectedItem().toString();
        String lamaSewaRaw = txtLamaSewa.getText();
        String totalHargaRaw = txtTotalHarga.getText();
        String tglPinjamRaw = txtTglPinjam.getText();

    if (controller.prosesSimpanTransaksi(selectedCustomer, selectedVehicle, idUserLogin, lamaSewaRaw, totalHargaRaw, tglPinjamRaw)) {
        JOptionPane.showMessageDialog(this, "Transaksi Berhasil Disimpan!");
        resetForm();
        loadDataKendaraanDariSQL(); 
        loadDataTransaksiKeTable();  
            } else {
        JOptionPane.showMessageDialog(this, "Gagal menyimpan transaksi! Cek kembali inputan.");
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtTglPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTglPinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTglPinjamActionPerformed

    private void txtHargaSewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaSewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaSewaActionPerformed

    private void txtMerekKendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMerekKendaraanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMerekKendaraanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        resetForm();
        txtMerekKendaraan.setText("");
        txtHargaSewa.setText("0");
        txtTglPinjam.setText("YYYY-MM-YY"); 
        if (cmbCustomer.getItemCount() > 0) cmbCustomer.setSelectedIndex(0);
        if (cmbKendaraan.getItemCount() > 0) cmbKendaraan.setSelectedIndex(0);
        JOptionPane.showMessageDialog(this, "Form berhasil dibersihkan!");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtMerekKendaraanComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txtMerekKendaraanComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMerekKendaraanComponentResized

    private void cmbKendaraanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbKendaraanItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED && cmbKendaraan.getSelectedItem() != null) {
        try {
            // 1. Ambil ID kendaraan dari teks ComboBox 
            String idTerpilih = cmbKendaraan.getSelectedItem().toString().split(" - ")[0];
            
            // 2. Minta daftar data kendaraan asli dari Controller
            java.util.List<String[]> listKendaraan = controller.ambilKendaraan();
            
            for (String[] kendaraan : listKendaraan) {
        if (kendaraan[0].equals(idTerpilih)) {
            txtMerekKendaraan.setText(kendaraan[1]); 
            txtHargaSewa.setText(kendaraan[3]);         
            updateOtomatisTotalBayar();
            break;
                }
            }
        } catch (Exception e) {
            System.out.println("Gagal memuat detail kendaraan: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_cmbKendaraanItemStateChanged

    private void txtLamaSewaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLamaSewaKeyReleased
        // TODO add your handling code here:
        updateOtomatisTotalBayar();
    }//GEN-LAST:event_txtLamaSewaKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    int barisTerpilih = jTable1.getSelectedRow();
    
    // 1. Validasi apakah user sudah memilih baris tabel yang mau dihapus
    if (barisTerpilih == -1) {
        JOptionPane.showMessageDialog(this, "Silakan pilih baris data pada tabel terlebih dahulu yang ingin dihapus!");
        return;
    }
    
    // 2. Ambil ID Transaksi (No. Nota) dari baris tabel kolom pertama (indeks 0)
    int idRental = Integer.parseInt(jTable1.getValueAt(barisTerpilih, 0).toString());
    String namaPelanggan = jTable1.getValueAt(barisTerpilih, 1).toString();
    
    // 3. Munculkan Pop-up Konfirmasi (Biar tidak sengaja ke-delete)
    int konfirmasi = JOptionPane.showConfirmDialog(this, 
            "Apakah Anda yakin ingin menghapus transaksi Nota No. " + idRental + " atas nama " + namaPelanggan + "?", 
            "Konfirmasi Hapus Data", 
            JOptionPane.YES_NO_OPTION);
            
    if (konfirmasi == JOptionPane.YES_OPTION) {
        // Tembak perintah hapus ke Controller asli kelompok
        if (controller.hapusTransaksi(idRental)) {
            JOptionPane.showMessageDialog(this, "Transaksi Berhasil Dihapus dari Database!");
            
            // 4. Refresh dan bersihkan tampilan visual form
            resetForm();
            loadDataKendaraanDariSQL(); // Update combobox kendaraan yang statusnya kembali 'Tersedia'
            loadDataTransaksiKeTable(); // Update isi tabel terbaru
        } else {
            JOptionPane.showMessageDialog(this, "Gagal menghapus transaksi! Silakan cek koneksi database.");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int barisTerpilih = jTable1.getSelectedRow();
    
    if (barisTerpilih != -1) {
        // Ambil No. Nota dari Kolom 0 (Indeks pertama di tabel)
        String noNota = jTable1.getValueAt(barisTerpilih, 0).toString();
    }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    
    private void resetForm() {
        txtLamaSewa.setText("0");
        txtTotalHarga.setText("0"); 
    }
    
    public static void bukaFormRental(int idUserAktif) {
        idUserLogin = idUserAktif;
        RentalForm form = new RentalForm();
        form.setVisible(true);
    }
    
private void loadDataCustomerDariSQL() {
    cmbCustomer.removeAllItems();
    
    // Menembak fungsi asli: ambilCustomer() yang menghasilkan List<String[]>
    java.util.List<String[]> listCustomer = controller.ambilCustomer();
    for (String[] customer : listCustomer) {
        // Gabungkan ID (indeks 0) dan Nama (indeks 1) untuk ComboBox
        cmbCustomer.addItem(customer[0] + " - " + customer[1]);
    }
}

private void loadDataKendaraanDariSQL() {
    cmbKendaraan.removeAllItems();
    
    // Menembak fungsi asli: ambilKendaraan()
    java.util.List<String[]> listKendaraan = controller.ambilKendaraan();
    for (String[] kendaraan : listKendaraan) {
        // Gabungkan ID/Plat (indeks 0) dan Merek (indeks 1)
        cmbKendaraan.addItem(kendaraan[0] + " - " + kendaraan[2]);
    }
}

private void loadDataTransaksiKeTable() {
    javax.swing.table.DefaultTableModel modelTabel = (javax.swing.table.DefaultTableModel) jTable1.getModel();
    modelTabel.setRowCount(0); // Bersihkan baris tabel agar tidak menumpuk
    
    //Menembak fungsi asli: ambilTabelTransaksi()
    java.util.List<String[]> listTransaksi = controller.ambilTabelTransaksi();
    for (String[] barisData : listTransaksi) {
        // Masukkan data array String secara utuh sebagai baris tabel baru
        modelTabel.addRow(barisData);
    }
}
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RentalForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbCustomer;
    private javax.swing.JComboBox<String> cmbKendaraan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtHargaSewa;
    private javax.swing.JTextField txtLamaSewa;
    private javax.swing.JTextField txtMerekKendaraan;
    private javax.swing.JTextField txtTglPinjam;
    private javax.swing.JTextField txtTotalHarga;
    // End of variables declaration//GEN-END:variables
}
