/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.ReportDAO;
import java.text.NumberFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class ReportForm extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(ReportForm.class.getName());
 
    private static final DateTimeFormatter TANGGAL_FORMAT =
            DateTimeFormatter.ofPattern("yyyy-MM-dd");
 
    private static final NumberFormat RUPIAH_FORMAT =
            NumberFormat.getNumberInstance(new Locale("in", "ID"));
 
    private final ReportDAO reportDAO = new ReportDAO();
    
    

    /**
     * Creates new form ReportForm
     */
    public ReportForm() {
        initComponents();
        setLocationRelativeTo(null);
        jTextFieldTotalPendapatan.setEditable(false);
        tampilkanLaporan(); // langsung tampilkan seluruh data saat form dibuka
    }
    
    /**
     * Mengambil & menampilkan laporan dari {@link ReportDAO}, opsional
     * difilter berdasarkan rentang tanggal kembali yang diisi user.
     * Jika kedua field tanggal kosong, seluruh data laporan akan ditampilkan.
     */
    private void tampilkanLaporan() {
        String tanggalDari = jTextFieldTanggalDari.getText().trim();
        String tanggalSampai = jTextFieldSampai.getText().trim();
 
        if (!isRentangTanggalValid(tanggalDari, tanggalSampai)) {
            return;
        }
 
        DefaultTableModel model = reportDAO.getLaporan(tanggalDari, tanggalSampai);
        jTable2.setModel(model);
 
        double totalPendapatan = reportDAO.getTotalPendapatan(tanggalDari, tanggalSampai);
        jTextFieldTotalPendapatan.setText(RUPIAH_FORMAT.format(totalPendapatan));
 
        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Data laporan tidak ditemukan.");
        }
    }
    
    /**
     * Validasi input tanggal sebelum dikirim ke database:
     * - Boleh dikosongkan berdua (artinya: tampilkan semua data tanpa filter).
     * - Kalau salah satu diisi, keduanya wajib diisi dengan format yyyy-MM-dd.
     * - Tanggal "Dari" tidak boleh melewati tanggal "Sampai".
     */
    private boolean isRentangTanggalValid(String tanggalDari, String tanggalSampai) {
        boolean dariKosong = tanggalDari.isEmpty();
        boolean sampaiKosong = tanggalSampai.isEmpty();
 
        if (dariKosong && sampaiKosong) {
            return true;
        }
 
        if (dariKosong != sampaiKosong) {
            JOptionPane.showMessageDialog(this,
                    "Isi kedua tanggal (Dari & Sampai) untuk memfilter laporan.");
            return false;
        }
 
        try {
            LocalDate dari = LocalDate.parse(tanggalDari, TANGGAL_FORMAT);
            LocalDate sampai = LocalDate.parse(tanggalSampai, TANGGAL_FORMAT);
 
            if (dari.isAfter(sampai)) {
                JOptionPane.showMessageDialog(this,
                        "Tanggal 'Dari' tidak boleh setelah tanggal 'Sampai'.");
                return false;
            }
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this,
                    "Format tanggal salah. Gunakan format yyyy-MM-dd, contoh: 2026-07-01");
            return false;
        }
 
        return true;
    }
    
     /** Mengosongkan filter tanggal lalu menampilkan ulang seluruh laporan. */
    private void resetForm() {
        jTextFieldTanggalDari.setText("");
        jTextFieldSampai.setText("");
        tampilkanLaporan();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabelJudulReport = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldTanggalDari = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldSampai = new javax.swing.JTextField();
        jButtonTampilkanLaporan = new javax.swing.JButton();
        jButtonRefresh = new javax.swing.JButton();
        jButtonKembali = new javax.swing.JButton();
        jScrollPaneReport = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldTotalPendapatan = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelJudulReport.setText("LAPORAN PENGEMBALIAN DAN PENDATAAN");

        jLabel12.setText("Tanggal Dari : ");

        jTextFieldTanggalDari.addActionListener(this::jTextFieldTanggalDariActionPerformed);

        jLabel1.setText("Sampai :");

        jTextFieldSampai.addActionListener(this::jTextFieldSampaiActionPerformed);

        jButtonTampilkanLaporan.setText("Tampilan Laporan");
        jButtonTampilkanLaporan.addActionListener(this::jButtonTampilkanLaporanActionPerformed);

        jButtonRefresh.setText("Refresh");
        jButtonRefresh.addActionListener(this::jButtonRefreshActionPerformed);

        jButtonKembali.setText("Kembali");
        jButtonKembali.addActionListener(this::jButtonKembaliActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTanggalDari, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldSampai, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 39, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabelJudulReport, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonTampilkanLaporan)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRefresh)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonKembali)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelJudulReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldTanggalDari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldSampai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTampilkanLaporan)
                    .addComponent(jButtonRefresh)
                    .addComponent(jButtonKembali))
                .addContainerGap())
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Rental", "Pelanggan", "Kendaraan", "Tgl Sewa", "Tgl Kembali", "Denda", "Total Bayar"
            }
        ));
        jScrollPaneReport.setViewportView(jTable2);

        jLabel2.setText("Total Pendapatan : Rp");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneReport)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTotalPendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneReport, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldTotalPendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSampaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSampaiActionPerformed
        // TODO add your handling code here:
        tampilkanLaporan();
    }//GEN-LAST:event_jTextFieldSampaiActionPerformed

    private void jButtonTampilkanLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTampilkanLaporanActionPerformed
        // TODO add your handling code here:
        tampilkanLaporan();
    }//GEN-LAST:event_jButtonTampilkanLaporanActionPerformed

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    private void jButtonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKembaliActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonKembaliActionPerformed

    private void jTextFieldTanggalDariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTanggalDariActionPerformed
        // TODO add your handling code here:
        tampilkanLaporan();
    }//GEN-LAST:event_jTextFieldTanggalDariActionPerformed

    /**
     * @param args the command line arguments
     */
     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
 
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReportForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonKembali;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JButton jButtonTampilkanLaporan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelJudulReport;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneReport;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextFieldSampai;
    private javax.swing.JTextField jTextFieldTanggalDari;
    private javax.swing.JTextField jTextFieldTotalPendapatan;
    // End of variables declaration//GEN-END:variables
}
