/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ReturnController;
 
import java.sql.Date;
import java.util.List;
 
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class ReturnForm extends javax.swing.JFrame {
   private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(ReturnForm.class.getName());
 
   private controller.ReturnController controller;
    private DefaultTableModel model;
    private int totalHargaSewa = 0;
            
    /**
     * Creates new form ReturnForm
     */
    public ReturnForm() {
        initComponents();
        setLocationRelativeTo(null);
        buatTabel();
        this.controller = new controller.ReturnController(this);
        //tampilkanRentalBelumKembali();
 
        jTextFieldNamaPelanggan.setEditable(false);
        jTextFieldNamaKendaraan.setEditable(false);
        jTextFieldRencanaKembali.setEditable(false);
        jTextFieldTerlambat.setEditable(false);
        jTextFieldDenda.setEditable(false);
        jTextFieldTotalBayar.setEditable(false);
    }
    
    private void buatTabel() {
        model = new DefaultTableModel();
 
        model.addColumn("ID Rental");
        model.addColumn("Pelanggan");
        model.addColumn("Kendaraan");
        model.addColumn("Tgl Sewa");
        model.addColumn("Rencana Kembali");
 
        jTableRental.setModel(model);
    }
 
    private void tampilkanRentalBelumKembali() {
       
    }   
 
    public void kosongkanForm() {
        jTextFieldIdRental.setText("");
        jTextFieldNamaPelanggan.setText("");
        jTextFieldNamaKendaraan.setText("");
        jTextFieldRencanaKembali.setText("");
        jTextFieldDikembali.setText("");
        jTextFieldTerlambat.setText("");
        jTextFieldDenda.setText("");
        jTextFieldTotalBayar.setText("");
        jComboBoxKondisi.setSelectedIndex(0);
 
        totalHargaSewa = 0;
    }

   
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldIdRental = new javax.swing.JTextField();
        jTextFieldNamaPelanggan = new javax.swing.JTextField();
        jTextFieldNamaKendaraan = new javax.swing.JTextField();
        jTextFieldRencanaKembali = new javax.swing.JTextField();
        jTextFieldDikembali = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldTerlambat = new javax.swing.JTextField();
        jTextFieldDenda = new javax.swing.JTextField();
        jComboBoxKondisi = new javax.swing.JComboBox<>();
        jTextFieldTotalBayar = new javax.swing.JTextField();
        jButtonCari = new javax.swing.JButton();
        jButtonHitung = new javax.swing.JButton();
        jButtonSimpan = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jButtonKembali = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableRental = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("FORM PENGEMBALIAN KENDARAAN");

        jLabel2.setText("ID Rental");

        jLabel3.setText("Nama Pelanggan");

        jLabel4.setText("Nama Kendaraan");

        jLabel5.setText("Tanggal Rencana Kembali");

        jLabel6.setText("Tanggal Dikembalikan");

        jTextFieldRencanaKembali.addActionListener(this::jTextFieldRencanaKembaliActionPerformed);

        jTextFieldDikembali.addActionListener(this::jTextFieldDikembaliActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(159, 159, 159)
                        .addComponent(jTextFieldIdRental))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNamaPelanggan)
                            .addComponent(jTextFieldNamaKendaraan)
                            .addComponent(jTextFieldRencanaKembali)
                            .addComponent(jTextFieldDikembali))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(126, 126, 126))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldIdRental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldNamaKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldRencanaKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldDikembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setText("Terlambat (Hari)");

        jLabel8.setText("Denda");

        jLabel9.setText("Kondisi Kendaraan");

        jLabel10.setText("Total Bayar");

        jComboBoxKondisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baik", "Lecet Ringan", "Rusak", "Perlu Diservis" }));
        jComboBoxKondisi.addActionListener(this::jComboBoxKondisiActionPerformed);

        jButtonCari.setText("Cari Data");
        jButtonCari.addActionListener(this::jButtonCariActionPerformed);

        jButtonHitung.setText("Hitung Denda");
        jButtonHitung.addActionListener(this::jButtonHitungActionPerformed);

        jButtonSimpan.setText("Simpan");
        jButtonSimpan.addActionListener(this::jButtonSimpanActionPerformed);

        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(this::jButtonResetActionPerformed);

        jButtonKembali.setText("Kembali");
        jButtonKembali.addActionListener(this::jButtonKembaliActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(147, 147, 147)
                        .addComponent(jTextFieldTotalBayar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(108, 108, 108)
                        .addComponent(jComboBoxKondisi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(119, 119, 119)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldTerlambat)
                            .addComponent(jTextFieldDenda)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButtonCari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonHitung)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonKembali)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldTerlambat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldDenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jComboBoxKondisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCari)
                    .addComponent(jButtonHitung)
                    .addComponent(jButtonSimpan)
                    .addComponent(jButtonReset)
                    .addComponent(jButtonKembali))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableRental.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Rental", "Pelanggan", "Kendaraan", "Tgl Sewa", "Rencana Kembali"
            }
        ));
        jTableRental.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableRentalMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableRental);

        jButton1.setText("<< Prev");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Next >>");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jButton1)
                .addGap(84, 84, 84)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCariActionPerformed
        // TODO add your handling code here:
         controller.cariData();
    }//GEN-LAST:event_jButtonCariActionPerformed

    private void jButtonHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHitungActionPerformed
        // TODO add your handling code here:
        controller.hitungDenda();
    }//GEN-LAST:event_jButtonHitungActionPerformed

    private void jButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanActionPerformed
        // TODO add your handling code here:
       controller.simpanPengembalian();
    }//GEN-LAST:event_jButtonSimpanActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        kosongkanForm();
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKembaliActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonKembaliActionPerformed

    private void jTextFieldRencanaKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRencanaKembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRencanaKembaliActionPerformed

    private void jTextFieldDikembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDikembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDikembaliActionPerformed

    private void jComboBoxKondisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxKondisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxKondisiActionPerformed

    private void jTableRentalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRentalMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jTableRentalMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        controller.returnPrev();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        controller.returnNext();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public javax.swing.JTextField getTxtIdRental() { return jTextFieldIdRental; }
    public javax.swing.JTextField getTxtNamaPelanggan() { return jTextFieldNamaPelanggan; }
    public javax.swing.JTextField getTxtNamaKendaraan() { return jTextFieldNamaKendaraan; }
    public javax.swing.JTextField getTxtRencanaKembali() { return jTextFieldRencanaKembali; }
    public javax.swing.JTextField getTxtDikembali() { return jTextFieldDikembali; }
    public javax.swing.JTextField getTxtTerlambat() { return jTextFieldTerlambat; }
    public javax.swing.JTextField getTxtDenda() { return jTextFieldDenda; }
    public javax.swing.JTextField getTxtTotalBayar() { return jTextFieldTotalBayar; }
    public int getTotalHargaSewa() { return totalHargaSewa; }
    public void setTotalHargaSewa(int total) { this.totalHargaSewa = total; }
    public javax.swing.JTable getjTableRental() { return jTableRental; }
    
    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info
                    : javax.swing.UIManager.getInstalledLookAndFeels()) {

            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ReflectiveOperationException
            | javax.swing.UnsupportedLookAndFeelException ex) {

        java.util.logging.Logger.getLogger(ReturnForm.class.getName())
                .log(java.util.logging.Level.SEVERE, null, ex);
    }

    java.awt.EventQueue.invokeLater(() -> {
        new ReturnForm().setVisible(true);
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonCari;
    private javax.swing.JButton jButtonHitung;
    private javax.swing.JButton jButtonKembali;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JComboBox<String> jComboBoxKondisi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableRental;
    private javax.swing.JTextField jTextFieldDenda;
    private javax.swing.JTextField jTextFieldDikembali;
    private javax.swing.JTextField jTextFieldIdRental;
    private javax.swing.JTextField jTextFieldNamaKendaraan;
    private javax.swing.JTextField jTextFieldNamaPelanggan;
    private javax.swing.JTextField jTextFieldRencanaKembali;
    private javax.swing.JTextField jTextFieldTerlambat;
    private javax.swing.JTextField jTextFieldTotalBayar;
    // End of variables declaration//GEN-END:variables

    
    
    public Object getTxtReturnId() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}

