/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import config.Koneksi;
import controller.ReturnController;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ReturnTransaction;


/**
 *
 * @author user
 */
public class ReturnForm extends javax.swing.JFrame {
    private ReturnController controller = new ReturnController();
    private DefaultTableModel model;
    private double totalBiayaSewa = 0;
    

    /**
     * Creates new form ReturnForm
     */
    public ReturnForm() {
        initComponents();
        setLocationRelativeTo(null);
        buatTabel();
        tampilkanRentalBelumKembali();
        
        jTextFieldNamaPelanggan.setEditable(false);
        jTextFieldNamaKendaraan.setEditable(false);
        jTextFieldRencanaKembali.setEditable(false);
        jTextFieldTerlambat.setEditable(false);
        jTextFieldDenda.setEditable(false);
        jTextFieldTotalBayar.setEditable(false);
    }
    
    private void buatTabel() {
        model = new DefaultTableModel();
        
        model.addColumn("ID Rental");
        model.addColumn("Pelanggan");
        model.addColumn("Kendaraan");
        model.addColumn("Tgl Sewa");
        model.addColumn("Rencana Kembali");
    
        jTableRental.setModel(model);
    }
    
    private void tampilkanRentalBelumKembali() {
        model.setRowCount(0);
         
        try {
            Connection conn = Koneksi.getConnection(); 
            
            String sql = "SELECT r.id_rental, c.nama_customer, "
                + "v.nama_vehicle, r.tanggal_sewa, "
                + "r.tanggal_rencana_kembali "
                + "FROM rentals r "
                + "INNER JOIN customers c ON r.id_customer = c.id_customer "
                + "INNER JOIN vehicles v ON r.id_vehicle = v.id_vehicle "
                + "WHERE r.status_rental = 'Disewa'";
            
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            
             while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("id_rental"),
                rs.getString("nama_customer"),
                rs.getString("nama_vehicle"),
                rs.getDate("tanggal_sewa"),
                rs.getDate("tanggal_rencana_kembali")
                });    
            }
            
         } catch (Exception e) {
             JOptionPane.showMessageDialog(this,
                      "Gagal menampilkan data rental: " + e.getMessage());
        }
    }
    
    private void kosongkanForm() {
    jTextFieldIdRental.setText("");
    jTextFieldNamaPelanggan.setText("");
    jTextFieldNamaKendaraan.setText("");
    jTextFieldRencanaKembali.setText("");
    jTextFieldDikembali.setText("");
    jTextFieldTerlambat.setText("");
    jTextFieldDenda.setText("");
    jTextFieldTotalBayar.setText("");
    jComboBoxKondisi.setSelectedIndex(0);

    totalBiayaSewa = 0;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldIdRental = new javax.swing.JTextField();
        jTextFieldNamaPelanggan = new javax.swing.JTextField();
        jTextFieldNamaKendaraan = new javax.swing.JTextField();
        jTextFieldRencanaKembali = new javax.swing.JTextField();
        jTextFieldDikembali = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldTerlambat = new javax.swing.JTextField();
        jTextFieldDenda = new javax.swing.JTextField();
        jComboBoxKondisi = new javax.swing.JComboBox<>();
        jTextFieldTotalBayar = new javax.swing.JTextField();
        jButtonCari = new javax.swing.JButton();
        jButtonHitung = new javax.swing.JButton();
        jButtonSimpan = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jButtonKembali = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableRental = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("FORM PENGEMBALIAN KENDARAAN");

        jLabel2.setText("ID Rental");

        jLabel3.setText("Nama Pelanggan");

        jLabel4.setText("Nama Kendaraan");

        jLabel5.setText("Tanggal Rencana Kembali");

        jLabel6.setText("Tanggal Dikembalikan");

        jTextFieldRencanaKembali.addActionListener(this::jTextFieldRencanaKembaliActionPerformed);

        jTextFieldDikembali.addActionListener(this::jTextFieldDikembaliActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(159, 159, 159)
                        .addComponent(jTextFieldIdRental))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNamaPelanggan)
                            .addComponent(jTextFieldNamaKendaraan)
                            .addComponent(jTextFieldRencanaKembali)
                            .addComponent(jTextFieldDikembali))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldIdRental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldNamaKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldRencanaKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldDikembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setText("Terlambat (Hari)");

        jLabel8.setText("Denda");

        jLabel9.setText("Kondisi Kendaraan");

        jLabel10.setText("Total Bayar");

        jComboBoxKondisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baik", "Lecet Ringan", "Rusak", "Perlu Diservis" }));
        jComboBoxKondisi.setSelectedItem(ReturnController);

        jButtonCari.setText("Cari Data");
        jButtonCari.addActionListener(this::jButtonCariActionPerformed);

        jButtonHitung.setText("Hitung Denda");
        jButtonHitung.addActionListener(this::jButtonHitungActionPerformed);

        jButtonSimpan.setText("Simpan");
        jButtonSimpan.addActionListener(this::jButtonSimpanActionPerformed);

        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(this::jButtonResetActionPerformed);

        jButtonKembali.setText("Kembali");
        jButtonKembali.addActionListener(this::jButtonKembaliActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(147, 147, 147)
                        .addComponent(jTextFieldTotalBayar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(108, 108, 108)
                        .addComponent(jComboBoxKondisi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(119, 119, 119)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldTerlambat)
                            .addComponent(jTextFieldDenda)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButtonCari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonHitung)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonKembali)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldTerlambat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldDenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jComboBoxKondisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCari)
                    .addComponent(jButtonHitung)
                    .addComponent(jButtonSimpan)
                    .addComponent(jButtonReset)
                    .addComponent(jButtonKembali))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableRental.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Rental", "Pelanggan", "Kendaraan", "Tgl Sewa", "Rencana Kembali"
            }
        ));
        jScrollPane3.setViewportView(jTableRental);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCariActionPerformed
        // TODO add your handling code here:
        try {
            int idRental = Integer.parseInt(jTextFieldIdRental.getText());

            Connection conn = Koneksi.getConnection();

            String sql = "SELECT c.nama_customer, v.nama_vehicle, "
            + "r.tanggal_rencana_kembali, r.total_biaya "
            + "FROM rentals r "
            + "INNER JOIN customers c ON r.id_customer = c.id_customer "
            + "INNER JOIN vehicles v ON r.id_vehicle = v.id_vehicle "
            + "WHERE r.id_rental = ? AND r.status_rental = 'Disewa'";

            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, idRental);

            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                jTextFieldNamaPelanggan.setText(rs.getString("nama_customer"));
                jTextFieldNamaKendaraan.setText(rs.getString("nama_vehicle"));
                jTextFieldRencanaKembali.setText(
                    rs.getDate("tanggal_rencana_kembali").toString()
                );

                totalBiayaSewa = rs.getDouble("total_biaya");

            } else {
                JOptionPane.showMessageDialog(this,
                    "ID rental tidak ditemukan atau sudah dikembalikan.");
                kosongkanForm();
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "ID Rental harus berupa angka.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Gagal mencari data: " + e.getMessage());
        }
        
    }//GEN-LAST:event_jButtonCariActionPerformed

    private void jButtonHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHitungActionPerformed
        // TODO add your handling code here:
        try {
            if (jTextFieldRencanaKembali.getText().isEmpty()
                || jTextFieldDikembali.getText().isEmpty()) {

                JOptionPane.showMessageDialog(this,
                    "Cari data rental dan isi tanggal dikembalikan terlebih dahulu.");
                return;
            }

            Date tanggalRencana = Date.valueOf(jTextFieldRencanaKembali.getText());
            Date tanggalKembali = Date.valueOf(jTextFieldDikembali.getText());

            int terlambatHari = controller.hitungTerlambatHari(
                tanggalRencana, tanggalKembali
            );

            double denda = controller.hitungDenda(terlambatHari);
            double totalBayar = totalBiayaSewa + denda;

            jTextFieldTerlambat.setText(String.valueOf(terlambatHari));
            jTextFieldDenda.setText(String.valueOf(denda));
            jTextFieldTotalBayar.setText(String.valueOf(totalBayar));

        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this,
                "Format tanggal harus yyyy-MM-dd. Contoh: 2026-07-05");
        }
    }//GEN-LAST:event_jButtonHitungActionPerformed

    private void jButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanActionPerformed
        // TODO add your handling code here:
        try {
            if (jTextFieldIdRental.getText().isEmpty()
                || jTextFieldDikembali.getText().isEmpty()
                || jTextFieldTotalBayar.getText().isEmpty()) {

                JOptionPane.showMessageDialog(this,
                    "Lengkapi data dan klik Hitung Denda terlebih dahulu.");
                return;
            }

            int idRental = Integer.parseInt(jTextFieldIdRental.getText());

            if (controller.sudahDikembalikan(idRental)) {
                JOptionPane.showMessageDialog(this,
                    "Rental ini sudah pernah dikembalikan.");
                return;
            }

            ReturnTransaction dataReturn = new ReturnTransaction();

            dataReturn.setIdRental(idRental);
            dataReturn.setTanggalKembali(
                Date.valueOf(jTextFieldDikembali.getText())
            );
            dataReturn.setTerlambatHari(
                Integer.parseInt(jTextFieldTerlambat.getText())
            );
            dataReturn.setDenda(
                Double.parseDouble(jTextFieldDenda.getText())
            );
            dataReturn.setKondisiKendaraan(
                jComboBoxKondisi.getSelectedItem().toString()
            );
            dataReturn.setTotalBayar(
                Double.parseDouble(jTextFieldTotalBayar.getText())
            );

            if (controller.simpanPengembalian(dataReturn)) {
                kosongkanForm();
                tampilkanRentalBelumKembali();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Gagal menyimpan data: " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonSimpanActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        kosongkanForm();
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKembaliActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonKembaliActionPerformed

    private void jTextFieldRencanaKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRencanaKembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRencanaKembaliActionPerformed

    private void jTextFieldDikembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDikembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDikembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReturnForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCari;
    private javax.swing.JButton jButtonHitung;
    private javax.swing.JButton jButtonKembali;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JComboBox<String> jComboBoxKondisi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableRental;
    private javax.swing.JTextField jTextFieldDenda;
    private javax.swing.JTextField jTextFieldDikembali;
    private javax.swing.JTextField jTextFieldIdRental;
    private javax.swing.JTextField jTextFieldNamaKendaraan;
    private javax.swing.JTextField jTextFieldNamaPelanggan;
    private javax.swing.JTextField jTextFieldRencanaKembali;
    private javax.swing.JTextField jTextFieldTerlambat;
    private javax.swing.JTextField jTextFieldTotalBayar;
    // End of variables declaration//GEN-END:variables
}
