/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import model.Vehicle;
import controller.VehicleController;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class VehicleForm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VehicleForm.class.getName());

    /**
     * Creates new form VehicleForm
     */
    //menampung id student untuk edit
    private Integer selectedIDVehicle;
    VehicleController controller = new VehicleController();
    final String[] statusVehicle = {"Tersedia", "Disewa"};
    final DefaultComboBoxModel comboStatusVehicle = new DefaultComboBoxModel(statusVehicle);
    final String[] tipeVehicle = {"Mobil", "Motor"};
    final DefaultComboBoxModel comboTipeVehicle = new DefaultComboBoxModel(tipeVehicle);

    public VehicleForm() throws SQLException {
        initComponents();
        loadVehicleData();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void loadVehicleData() throws SQLException {
        controller.muatDataAwal(this);
    }

    private void clearForm() {
        jTextFieldIdKendaraan.setText("");
        jTextFieldNoPlat.setText("");
        jTextFieldMerek.setText("");
        jTextFieldHargaSewa.setText("");
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelIdKendaraan = new javax.swing.JLabel();
        jLabelNoPlat = new javax.swing.JLabel();
        jLabelMerek = new javax.swing.JLabel();
        jTextFieldIdKendaraan = new javax.swing.JTextField();
        jTextFieldNoPlat = new javax.swing.JTextField();
        jTextFieldMerek = new javax.swing.JTextField();
        jLabelMerek1 = new javax.swing.JLabel();
        jLabelMerek2 = new javax.swing.JLabel();
        jLabelMerek3 = new javax.swing.JLabel();
        jTextFieldHargaSewa = new javax.swing.JTextField();
        jComboBoxTipeKendaraan = new javax.swing.JComboBox<>();
        jComboBoxStatus = new javax.swing.JComboBox<>();
        jButtonSimpan = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonRiset = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCari = new javax.swing.JTextField();
        jButtonCari = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableVehicle = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jButton2.setText("jButton2");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Manajemen Data Kendaraan");

        jLabelIdKendaraan.setText("ID Kendaraan");

        jLabelNoPlat.setText("No Plat");

        jLabelMerek.setText("Merek");

        jTextFieldMerek.addActionListener(this::jTextFieldMerekActionPerformed);

        jLabelMerek1.setText("Tipe Kendaraan");

        jLabelMerek2.setText("Harga Sewa / Hari");

        jLabelMerek3.setText("Status");

        jTextFieldHargaSewa.addActionListener(this::jTextFieldHargaSewaActionPerformed);

        jComboBoxTipeKendaraan.setModel(comboTipeVehicle);
        jComboBoxTipeKendaraan.addActionListener(this::jComboBoxTipeKendaraanActionPerformed);

        jComboBoxStatus.setModel(comboStatusVehicle);
        jComboBoxStatus.addActionListener(this::jComboBoxStatusActionPerformed);

        jButtonSimpan.setText("Simpan");
        jButtonSimpan.addActionListener(this::jButtonSimpanActionPerformed);

        jButtonDelete.setText("Hapus");
        jButtonDelete.addActionListener(this::jButtonDeleteActionPerformed);

        jButtonRiset.setText("Reset");
        jButtonRiset.addActionListener(this::jButtonRisetActionPerformed);

        jLabel2.setText("Cari No Plat / Merek");

        jTextFieldCari.addActionListener(this::jTextFieldCariActionPerformed);

        jButtonCari.setText("Cari");
        jButtonCari.addActionListener(this::jButtonCariActionPerformed);

        jButton4.setText("Kembali");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jButtonSimpan))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMerek1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelMerek, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelNoPlat, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelIdKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelMerek2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMerek3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldCari, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCari))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonDelete)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonRiset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldNoPlat, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldIdKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMerek, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxTipeKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldHargaSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdKendaraan)
                    .addComponent(jTextFieldIdKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNoPlat)
                    .addComponent(jTextFieldNoPlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldMerek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMerek))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTipeKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMerek1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldHargaSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMerek2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabelMerek3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSimpan)
                    .addComponent(jButtonDelete)
                    .addComponent(jButtonRiset)
                    .addComponent(jButton4))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCari))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jTableVehicle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Kendaraan", "No Plat", "Merek", "Tipe", "Harga Sewa", "Status"
            }
        ));
        jTableVehicle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableVehicleMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableVehicle);

        jButton1.setText("<< Prev");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton3.setText("Next >>");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jButton1)
                .addGap(77, 77, 77)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel1)
                        .addGap(0, 160, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldMerekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMerekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMerekActionPerformed

    private void jTextFieldHargaSewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHargaSewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHargaSewaActionPerformed

    private void jButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanActionPerformed
        // TODO add your handling code here:
//        Integer id_kendaraan = Integer.valueOf(jTextFieldIdKendaraan.getText());
        String no_plat = jTextFieldNoPlat.getText();
        String merek = jTextFieldMerek.getText();
        int harga_sewa = 0;
        if (!jTextFieldHargaSewa.getText().trim().matches("-?\\d+")) {
            JOptionPane.showMessageDialog(this, "Inputan Harga Sewa Harus Angka! ", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            harga_sewa = Integer.parseInt(jTextFieldHargaSewa.getText());
        }
        String tipe_kendaraan = jComboBoxTipeKendaraan.getSelectedItem().toString();
        
        String status_kendaraan = jComboBoxStatus.getSelectedItem().toString();

        if (no_plat.isEmpty() || merek.isEmpty() || jTextFieldHargaSewa.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Data Kendaraan Tidak Boleh Kosong! ", "Input Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Vehicle vehicle = new Vehicle(no_plat, merek, tipe_kendaraan, harga_sewa, status_kendaraan);
            try {
                //kenali apakah update atau data baru, bisa dilihat dari selectedNIM
                boolean res;
                if (selectedIDVehicle != null) {
                    //jika selectedNIm tidak Null
                    res = controller.updateKendaraan(vehicle, selectedIDVehicle);
                } else {
                    res = controller.simpanKendaraan(vehicle);
                }
                if (res) {
                    JOptionPane.showMessageDialog(this, "Data Kendaraan Berhasil Ditambahkan! ", "Success", JOptionPane.INFORMATION_MESSAGE);
                    this.selectedIDVehicle = null;
                    this.clearForm();
                    loadVehicleData();
                } else {
                    JOptionPane.showMessageDialog(this, "Terjadi Kesalahan Saat Menambahkan Data Kendaraan! ", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonSimpanActionPerformed

    private void jButtonRisetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRisetActionPerformed
        // TODO add your handling code here:
        this.clearForm();
    }//GEN-LAST:event_jButtonRisetActionPerformed

    private void jButtonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCariActionPerformed
        // TODO add your handling code here:
        String cari_kendaraan = jTextFieldCari.getText().trim();
        controller.cariKendaraanBagiPaginasi(cari_kendaraan, this);
    }//GEN-LAST:event_jButtonCariActionPerformed

    private void jComboBoxStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxStatusActionPerformed

    private void jComboBoxTipeKendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipeKendaraanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipeKendaraanActionPerformed

    private void jTextFieldCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCariActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this,
                "Apakah Anda Yakin Untuk Menghapus Data Kendaraan?",
                "Konfirmasi Hapus",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            // Proses delete
            try {
                controller.hapusKendaraan(selectedIDVehicle);
                JOptionPane.showMessageDialog(this, "Data Kendaraan Berhasil Dihapus!");
                this.selectedIDVehicle = null;
                this.clearForm();
                loadVehicleData();
            } catch (SQLException ex) {
                Logger.getLogger(VehicleForm.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Terjadi Kesalahan Saat Menghapus Data Kendaraan!");
            }
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jTableVehicleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableVehicleMouseClicked
        // TODO add your handling code here:
        int selectedRow = jTableVehicle.getSelectedRow();
        if (selectedRow != -1) {
            jTextFieldIdKendaraan.setEditable(false);
            selectedIDVehicle = Integer.valueOf(jTableVehicle.getValueAt(selectedRow, 0).toString());
            jTextFieldIdKendaraan.setText(jTableVehicle.getValueAt(selectedRow, 0).toString());
            jTextFieldNoPlat.setText(jTableVehicle.getValueAt(selectedRow, 1).toString());
            jTextFieldMerek.setText(jTableVehicle.getValueAt(selectedRow, 2).toString());
            jComboBoxTipeKendaraan.setSelectedItem(jTableVehicle.getValueAt(selectedRow, 3).toString());
            jTextFieldHargaSewa.setText(jTableVehicle.getValueAt(selectedRow, 4).toString());
            jComboBoxStatus.setSelectedItem(jTableVehicle.getValueAt(selectedRow, 5).toString());
        }
    }//GEN-LAST:event_jTableVehicleMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        controller.vehiclePrev(this);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        controller.vehicleNext(this);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed
    public javax.swing.JTable getjTableVehicle() {
    return jTableVehicle;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VehicleForm().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(VehicleForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonCari;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonRiset;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JComboBox<String> jComboBoxStatus;
    private javax.swing.JComboBox<String> jComboBoxTipeKendaraan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelIdKendaraan;
    private javax.swing.JLabel jLabelMerek;
    private javax.swing.JLabel jLabelMerek1;
    private javax.swing.JLabel jLabelMerek2;
    private javax.swing.JLabel jLabelMerek3;
    private javax.swing.JLabel jLabelNoPlat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableVehicle;
    private javax.swing.JTextField jTextFieldCari;
    private javax.swing.JTextField jTextFieldHargaSewa;
    private javax.swing.JTextField jTextFieldIdKendaraan;
    private javax.swing.JTextField jTextFieldMerek;
    private javax.swing.JTextField jTextFieldNoPlat;
    // End of variables declaration//GEN-END:variables
}
